config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'
  get 'signup' =>'users#new'
    resources :users

get 'login' => 'sessions#new'
post 'login' =>'sessions#create'
delete 'logout' =>'sessions#destroy'
root 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
   before_save {self.email = email.downcase }
   
   validates :name, presence: true, length:{ maximum: 50}
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true ,length:{ maximum: 255 },
       format: {with: VALID_EMAIL_REGEX},
       uniqueness: {case_sensitive: false}

   has_secure_password
   validates :password,length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
   
    if user && user.authenticate(params[:session][:password])
      log_in user
         redirect_to user
    else
       flash[:danger] = 'Invalid email/password combination' # Not quite right!
       render 'new'
    end
  end
  
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :logged_in_user,only: [:edit,:update]
before_action :correct_user,only: [:edit,:update]
  def new
     @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
     @user = User.new(user_params)
     if @user.save
        log_in @user
        flash[:success] = "User successfully logged in!"
       redirect_to @user
     else
       render 'new'
     end
  end

   def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
   if @user.update_attributes(user_params)
     flash[:success] = "Profile updated"
     redirect_to @user
   else
    render 'edit'
   end
  end

  def logged_in_user
   unless logged_in?
    store_location
    flash[:danger] = "Please log in."
    redirect_to login_url
   end
  end

 
  private
    def user_params
      params.require(:user).permit(:name,:email,:password,
           :password_confirmation)
    end

  

  def correct_user
    @user = User.find(params[:id])
    # redirect_to(root_url) unless current_user?(@user)
  redirect_to(root_url)    unless @user == current_user
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

   # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  # Returns true if the user is logged in,false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
	<% if logged_in? %>
	<%= link_to "Log out",logout_path,method: "delete" %>
	<% else %>
	  <%= link_to "Log in",login_path %>
	<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserA</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if logged_in? %>
	<%= link_to "Log out",logout_path,method: "delete" %>
	<% else %>
	  <%= link_to "Log in",login_path %>
	<% end %>
	<% flash.each do |message_type,message| %>
	<%= message %>
	<% end %>
<%= yield %>

</body>
</html>

app/views/shared/_error_massages.html.erb
  <% if @user.errors.any? %>
    The form contains
    <%= pluralize(@user.errors.count,"error") %>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>

app/views/users/edit.html.erb
<h1>Update your profile</h1>
<%= form_for(@user) do |f| %>
<%= render 'shared/error_massages' %>
<%= f.label :name %>
<%= f.email_field :name,class: 'form-control' %>
<%= f.label :email %>
<%= f.text_field :email,class: 'form-control' %>
<%= f.label :password %>
<%= f.password_field :password,class: 'form-control' %>
<%= f.label :password_confirmation,"Confirmation" %>
<%= f.password_field :password_confirmation,class:'form-control' %>
<%= f.submit "Save changes",class: "btn btn-primary"%>
<% end %>

app/views/users/new.html.erb
<body style="background:skyblue">
<center>
<h1 style="color:white" > Sign up </h1>
<%= form_for(@user) do |f| %>
 <%= render 'shared/error_massages' %><br>
 <h3><%= f.label :name %><br>
 <%= f.text_field :name %><br><br>
 <%= f.label :email %><br>
 <%= f.email_field :email %><br><br>
 <%= f.label :password %><br>
 <%= f.password_field :password %><br><br>
 <%= f.label :password_confirmation,"Confirmation" %><br>
 <%= f.password_field :password_confirmation %><br><br><br>
 <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
 
<%= @user.name %> <br>
<%= @user.email %>